name: Build multiple luci-app plugins with OpenWrt 24.10.2 SDK

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g. 1.0.0)'
        required: true
        default: '1.0.0'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository (with plugin source at root)
        uses: actions/checkout@v4

      - name: Install dependencies, download and extract OpenWrt SDK 24.10.2
        run: |
          sudo apt-get update
          sudo apt-get install -y zstd makeself
          wget https://downloads.openwrt.org/releases/24.10.2/targets/x86/64/openwrt-sdk-24.10.2-x86-64_gcc-12.3.0_musl.Linux-x86_64.tar.zst -O sdk.tar.zst
          tar --use-compress-program=unzstd -xf sdk.tar.zst
          SDK_DIR=$(ls -d openwrt-sdk-*)
          echo "SDK_DIR=$SDK_DIR" >> $GITHUB_ENV

      - name: Copy plugin folders from repo root into SDK package directory
        run: |
          cd ${{ env.SDK_DIR }}/package/
          for plugin in \
luci-app-argon-config \
luci-app-argone-config \
luci-app-autoipsetadder \
luci-app-autorepeater \
luci-app-autoshell \
luci-app-autotimeset \
luci-app-autoupdate \
luci-app-baidupcs-web \
luci-app-bandwidthd \
luci-app-beardropper \
luci-app-bypass \
luci-app-chatgpt-web \
luci-app-chinesesubfinder \
luci-app-chongyoung \
luci-app-chongyoung2.0 \
luci-app-clash \
luci-app-clouddrive2 \
luci-app-cloudflarespeedtest \
luci-app-codeserver \
luci-app-control-timewol \
luci-app-control-webrestriction \
luci-app-control-weburl \
luci-app-cupsd \
luci-app-daed-next \
luci-app-daed \
luci-app-ddns-go \
luci-app-ddnsto \
luci-app-demon \
luci-app-design-config \
luci-app-dnscrypt-proxy2 \
luci-app-dnsfilter \
luci-app-dnsmasq-ipset \
luci-app-dnsproxy \
luci-app-dockerman \
luci-app-dogcom \
luci-app-drawio \
luci-app-easymesh \
luci-app-easytier \
luci-app-easyupdate \
luci-app-emby \
luci-app-eqos \
luci-app-eqosplus \
luci-app-excalidraw \
luci-app-fakemesh \
luci-app-fchomo \
luci-app-feishuvpn \
luci-app-fileassistant \
luci-app-filebrowser \
luci-app-floatip \
luci-app-fullconenat \
luci-app-gecoosac \
luci-app-go-aliyundrive-webdav \
luci-app-godproxy \
luci-app-gogs \
luci-app-gost \
luci-app-gowebdav \
luci-app-guest-wifi \
luci-app-heimdall \
luci-app-homeassistant \
luci-app-homebridge \
luci-app-homeproxy \
luci-app-homeredirect \
luci-app-htreader \
luci-app-ikoolproxy \
luci-app-immich \
luci-app-internet-detector \
luci-app-iperf3-server \
luci-app-ipsec-server \
luci-app-iptvhelper \
luci-app-istoredup \
luci-app-istoreenhance \
luci-app-istorego \
luci-app-istorepanel \
luci-app-istorex \
luci-app-ittools \
luci-app-jackett \
luci-app-jellyfin \
luci-app-kodexplorer \
luci-app-koolproxyR \
luci-app-lanraragi \
luci-app-linkease \
luci-app-lucky \
luci-app-mac \
luci-app-macvlan \
luci-app-mail \
luci-app-memos \
luci-app-mentohust \
luci-app-mfun \
luci-app-minieap; do
            cp -r ../../$plugin ./
          done

      - name: Bat
