name: Build selected luci-app plugins

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
        default: '1.0.0'
      packages:
        description: '要编译的插件，逗号分隔'
        required: true
        default: 'luci-app-argon-config,luci-app-autoupdate,luci-app-bypass'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup SDK and copy source (略，参考之前流程)

      - name: Batch compile selected plugins
        run: |
          echo "输入的插件列表: ${{ github.event.inputs.packages }}"
          IFS=',' read -ra PKG_ARR <<< "${{ github.event.inputs.packages }}"
          cd ${{ env.SDK_DIR }}
          make defconfig
          for pkg in "${PKG_ARR[@]}"; do
            echo "编译插件 $pkg"
            make package/$pkg/compile V=s || echo "编译 $pkg 失败，继续..."
          done

      # 其余打包、上传等步骤照旧
